"""init

Revision ID: 4e1a3ffd0cbf
Revises: 
Create Date: 2024-10-03 20:26:04.442421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1a3ffd0cbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('breedID', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('origin', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('breedID')
    )
    op.create_table('kitten',
    sa.Column('kittenID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('breedID', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['breedID'], ['breed.breedID'], ),
    sa.PrimaryKeyConstraint('kittenID')
    )
    op.drop_table('kittens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kittens',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kittens_pkey')
    )
    op.drop_table('kitten')
    op.drop_table('breed')
    # ### end Alembic commands ###
